# Generated by Django 5.1.3 on 2024-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
