# Generated by Django 5.1.3 on 2024-12-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_coffee_image_alter_coffee_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.FloatField(),
        ),
    ]
