# Generated by Django 5.1.3 on 2024-12-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_coffee_description_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
