# Generated by Django 5.1.3 on 2025-02-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_cart_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
