# Generated by Django 5.1.3 on 2025-01-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_categoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
